name: Bump Versions

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '30 17 * * WED' # 12:30 EST on Wednesdays
  workflow_dispatch:

jobs:
  bump-versions:
    uses: viam-modules/common-workflows/.github/workflows/bump_go_dependencies.yaml@main
