name: Build and Publish RC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

# To test workflow updates you need to work in a branch directly on viamrobotics/viam-cartographer
# and tag your working branch instead of @main in any viamrobotics/viam-cartographer "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: ./.github/workflows/test.yml

  appimage:
    uses: ./.github/workflows/appimage.yml
    needs: test
    with:
      release_type: 'rc'
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
