name: Build and Publish Stable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

# To test workflow updates you need to work in a branch directly on viamrobotics/viam-cartographer
# and tag your working branch instead of @main in any viamrobotics/viam-cartographer "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  test:
    uses: ./.github/workflows/test.yml

  appimage:
  # remove
    uses: ./.github/workflows/appimage.yml
    needs: test
    with:
      release_type: 'stable'
    secrets:
      GCP_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

  slack-workflow-status:
    if: ${{ failure() }}
    name: Post Workflow Status To Slack
    needs:
      - test
      - appimage
    runs-on: ubuntu-latest
    permissions:
      actions: 'read'
    steps:
      - name: Slack Workflow Notification
        uses: Gamesight/slack-workflow-status@master
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          slack_webhook_url: ${{secrets.SLACK_WEBHOOK_URL}}
          channel: '#bucket-canary'
          name: 'Workflow Status'
